---
title: Publications
---
 
## Industrial Organization
- [Consumer Salience and Quality Provision in (Un)Regulated Public Service Markets](https://doi.org/10.1016/j.regsciurbeco.2021.103754) (with Alexander Rasch and Tobias Wenzel), [Ungated Working Paper](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3770534#), Regional Science and Urban Economics, March 2022


- [Data brokers co-opetition](https://doi.org/10.1093/oep/gpab042) (with Leo Madio and Carlo Reggiani), [Online Supplementary Material](https://drive.google.com/file/d/1zP3XYgIxemHS0oiaYfEk8W3yVi4B7Eom/view?usp=sharing), Oxford Economic Papers, July 2022


- [Curbing Obfuscation: Empower Consumers or Regulate Firms?](https://doi.org/10.1016/j.ijindorg.2020.102582) (with Tobias Wenzel), [Ungated Working Paper](https://drive.google.com/file/d/1sSYZEdMAJ6OCJsx5lFwJS7nhJ7f0-Jc2/view?usp=sharing), [Online Supplementary Material](https://drive.google.com/uc?export=download&id=1xjHHXdC60NJEAtLpkfV5q_2CMMymx18_), International Journal of Industrial Organization, May 2020

- [Consumer confusion, obfuscation, and price regulation](https://dx.doi.org/10.1111/sjpe.12121) (with Tobias Wenzel), [Ungated Working Paper](https://drive.google.com/file/d/1qnh7Oy3t_0jYmWWdwLFee3uyDDTe7C5a/view?usp=sharing), Scottish Journal of Political Economy, May 2017

- [Price-Sensitive Demand and Market Entry](http://doi.wiley.com/10.1111/pirs.12165) (with Alexander Rasch and Tobias Wenzel), [Ungated Working Paper](https://drive.google.com/file/d/1sv34gHkTMTIs8SIe1xTKZRQpD_LqIEBr/view?usp=sharing), Papers in Regional Science, November 2016

- [Putting on a Tight Leash and Levelling Playing Field: An Experiment in Strategic Obfuscation and Consumer Protection](http://dx.doi.org/10.1016/j.ijindorg.2015.07.008) (with Tobias Wenzel), [Ungated Working Paper](https://drive.google.com/file/d/110njAGds6h1NYnYsLpbJrMHu-6RTvixy/view?usp=sharing), International Journal of Industrial Organization, September 2015


- [Strategic obfuscation and consumer protection policy](http://dx.doi.org/10.1111/joie.12060) (with Tobias Wenzel), [Ungated Working Paper](https://drive.google.com/file/d/1smAoB8yOBVANAqTwx_jtInB5yWHZWzPU/view?usp=sharing), Journal of Industrial Economics, December 2014

- [Too much of a good thing? Welfare consequences of market transparency](https://www.jstor.org/stable/24548983)(with Burkhard Hehenkamp), [Ungated Working Paper](https://drive.google.com/file/d/1qhSjgax1k2Ftuy1Qw8n6wF67UC_o0hhQ/view?usp=sharing), Journal of Institutional and Theoretical Economics, June 2014


- [Transparency, Entry, and Productivity](http://dx.doi.org/10.1016/j.econlet.2011.11.016) (with Tobias Wenzel), [Ungated Working Paper](https://drive.google.com/file/d/1PWwykGbqasHOKWBAuOt4VdO4ZhJ5gLd6/view?usp=sharing), Economics Letters, April 2012


- [Price-Dependent Demand in Spatial Models](http://dx.doi.org/10.1515/1935-1682.3126) (with Tobias Wenzel), [Ungated Working Paper](https://drive.google.com/file/d/1Fj5lYR5QuMG76RPlde6xbTQ6lXjWeNz0/view?usp=sharing), B.E. Journal of Economic Analysis & Policy, March 2012


- [Transparency, Price-Dependent Demand and Product Variety](http://dx.doi.org/10.1016/j.econlet.2010.11.041) (with Tobias Wenzel), [Ungated Working Paper](https://drive.google.com/file/d/1TYvGh1HIgNRvs_wKRCxpmWh9RLcRCLen/view?usp=sharing), Economics Letters, March 2011

- [A Note on the Excess Entry Theorem in Spatial Models with Elastic Demand](http://dx.doi.org/10.1016/j.ijindorg.2009.01.002) (with Tobias Wenzel), [Ungated Working Paper](https://drive.google.com/file/d/132PeIyjAO5MnoM56_TRj3QDcQTc-_L4F/view?usp=sharing), International Journal of Industrial Organization, September 2009


## Housing and Land Economics 
- [Park Life: the difference between having financial information and understanding it on park home owners’ quality of life](https://centaur.reading.ac.uk/124436/) (with Alexander Lord, Richard Dunning, Ian Wilson and Tom Moore), [Ungated Working Paper](../papers/paper 8.0 final web.html), Town Planning Review, Forthcoming

- [Fair shares? Advancing land economics through cooperative game theory](https://dx.doi.org/10.1016/j.landusepol.2021.105400) (with Alexander Lord et. al.), Land Use Policy, July 2021

<!-- with A. Lord, A. Eika, P. Dethier, D.A. Samsura, B. I.Nordahl, D.E. Sommervoll,E. van der Krabben, J-M Halleux -->

- [Virtuous or vicious circles? Exploring the behavioural connections between developer contributions and path dependence: Evidence from England](https://doi.org/10.1016/j.geoforum.2019.07.024) (with Alexander Lord, Gemma Burgess and Richard Dunning), Geoforum, November 2019

- [Can the market be tamed? A thought experiment on the value(s) of planning](https://dx.doi.org/10.1177/0308518X18784600) (with Alexander Lord), Environment and Planning A: Economy and Space, February 2019


## Behavioural Foundations
- [Evolutionary Equilibrium in Contests with Stochastic Participation: Entry, Effort and Overdissipation](https://doi.org/10.1016/j.jebo.2019.06.011) (with Burkhard Hehenkamp and Wolfgang Leininger), [Ungated Working Paper](https://www.liverpool.ac.uk/media/livacuk/schoolofmanagement/research/economics/evolutionary-equilibrium-in-contests.pdf), Journal of Economic Behavior and Organization, August 2019

- [Bid outcome processing in Vickrey auctions: An ERP study](https://doi.org/10.1111/psyp.14125) (with Alice Newton-Fenner et. al.), Psychophysiology, June 2022

- [A comparison of reward processing during Becker–DeGroot–Marschak and Vickrey auctions: an ERP study](https://doi.org/10.1111/psyp.14313) (with Alice Newton-Fenner et. al.), Psychophysiology, April 2023

- [Economic value in the brain: a meta-analysis of willingness-to-pay using the Becker-DeGroot-Marschak auction](https://doi.org/10.1371/journal.pone.0286969), (with Alice Newton-Fenner et. al.), PLoS ONE, July 2023

